name: Go

on:
  push:
    tags: [ v* ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19

    - name: Build
      run: |
        go build -v ./... || exit 1
        mkdir bbdb-linux
        cp bbdb download.sh bbdb-linux
        tar czf bbdb-linux.tgz bbdb-linux

    - name: Package and Release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        artifacts: bbdb-linux.tgz
        allowUpdates: true
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        omitBody: true
        omitDraftDuringUpdate: true
        omitNameDuringUpdate: true
        omitPrereleaseDuringUpdate: true

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: Build
        run: |
          go build -v ./... || exit 1
          mkdir bbdb-mac
          cp bbdb download.sh bbdb-mac
          tar czf bbdb-mac.tgz bbdb-mac

      - name: Package and Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          artifacts: bbdb-mac.tgz
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          omitBody: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
